### ISSUE TITLE
Проверить флаги is_forecast, is_actual и is_previous

### ISSUE THREAD

**Issue by NewYaroslav** [NewYaroslav/forexprostools-cpp-api#2]
Судя по всему данные флаги не инициализируются во время записи новостей в хранилище данных. В итоге значение существует, но помечено как отсутствующее

**Comment by LimiNode** [comment]
Ошибка найдена. В методе read_news класса хранилища не происходит инициализации флагов.

**Comment by LimiNode** [comment]
Ошибку исправил
