### ISSUE TITLE
Error, file json cannot be opened!

### ISSUE THREAD

**Issue by bruev** [NewYaroslav/forexprostools-cpp-api#3]
forexprostools-downloader-15.exe /jf "forexprostools-downloader-settings.json"

Что ж не так-то? forexprostools-downloader-settings.json в той же директории..

**Comment by LimiNode** [comment]
У меня получилось воспроизвести ошибку, если пытаться выполнить именно вашу команду

`forexprostools-downloader-15.exe /jf "forexprostools-downloader-settings.json"`

Так как в папке bin этого репозитория нет файла forexprostools-downloader-settings.json, есть файл **forexprostools-downloader-settings-1.5.json**.

Попробуйте переименовать файл или команду

**Comment by LimiNode** [comment]
> forexprostools-downloader-15.exe /jf "forexprostools-downloader-settings.json"
> 
> Что ж не так-то? forexprostools-downloader-settings.json в той же директории..

Попробовали проверить имя файла?
